### ISSUE TITLE
Crash on unconfigured Core

### ISSUE THREAD

**Issue by AdamISZ** [JoinMarket-Org/JMBinary#1]
User report:

After doing some successful txs over the default blockr blockchain interface, switched to bitcoin-rpc and found that the application crashed (reliably). Two points to address:

1. App needs to recover gracefully if Bitcoin Core is not configured correctly (prob threw an exception, but on Win 8 and only got error message 'App returned -1').
2. Need to give very clear instructions on how to configure Core to work with joinmarket, including on windows; there are currently wiki articles [here](https://github.com/chris-belcher/joinmarket/wiki/Running-JoinMarket-with-Bitcoin-Core-full-node) and [here](https://github.com/JoinMarket-Org/joinmarket/wiki/Installing-JoinMarket-on-Windows-7-10-(temporary)), but user reported 'confused, all the script stuff', i.e. it's not helpful enough for non-technical people. Focus should be on how to modify bitcoin.conf, but note there might be an 'icky' part with `curl` here for Win users.

**Comment by chris-belcher** [comment]
You could have the app locate bitcoin.conf and add the notify lines itself

**Comment by AdamISZ** [comment]
1. : was fixed in version 4.

2: I think this will be an ongoing process.
