### ISSUE TITLE
ADAM DOES NOT GIVE HIS PUBLIC KEY 

### ISSUE THREAD

**Issue by cerberii** [JoinMarket-Org/JMBinary#3]
here is his public key for those that are struggling to find it

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: SKS 1.1.5
Comment: Hostname: pgp.mit.edu

mQENBFKrX/YBCACVnA/MUrGFrHPPbWSdYgeE6HbezMDJc1hp9mhOsEcW6+Fl7V1cs2jt61Ad
fRNa8n9z/CIblErat57nbiHe9KvYnw2vk5tQ45ZorU6Y/DiupfAOWoV0AirWiPYHA/0xFGoX
5YcGDpy0aWUNmIfdupDRhRTitKjwk8ttTheSS3frb6vJZhTtGlFGDXZP06RVc8qzL3QFfNy0
fT08egRdAGEJRnhhR3k80H3d7FBatxx9OD2VDaZuLLDwkmzaoH9SoiZSIQnBAPaNZPnT6ZX8
B4I9sMp5NmV9MmAmUd+IqzZjFOSI5+UnxfxpmtWfJO/QNzN+5uh3bV6P3iG9Fy+vhP1XABEB
AAG0IEFkYW0gR2lic29uIDxla2FnZ2F0YUBnbWFpbC5jb20+iQEcBBABCAAGBQJXIe2KAAoJ
ENpTF1oEI3343FIIAJ9fnL6fs750BqB+FUXz6MLhpHqJRl9pNU3wcDgXPkAALNa1rNLhWETD
zprSsRrcuWX5/dwOAWLJe/O0Nc7AoRdTwaEkNIFba4c6esFziFoajIo8UFnDgiPNWpiVBhMU
mwajSDg+h0TSDJgcyYwcPejuPlwpwiz6k/K3uvSOaVEZrRVuJA0cUspdttDlnfh/4jpDY2Mt
RRACdRo8Z+6hmua1So536KulfNxj4yVQtmnKW5vdx6ML+ydM0EREJp1XrpYVNgi+QyzszXck
Uoyc89EAnuSkF3CoUo8DQoj2jRhvh5kFzjB/Wv2lBC/tjM0O4UsEDB+DdGAwLL/mZUwZ69mJ
AT4EEwECACgFAlKrX/YCGyMFCQlmAYAGCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJELOu
CfHpoxl6yu4IAIS+povQ1EMz10G4te5TnCoIVW3dvazIebX+CoIC4tTMOyvuFLmi4NcaNIER
eX14NCbgaWPVFpvD07ijcP2gv1uq5cBzrb2nEM5vtEsrOszxx1hHO34G1wJETF8nVle7kA9G
wViMSl7WvUmTE8z4rcR7TdlDHv7vO0VIzbR9KqEtLfIGe/9XyV6Di8bW4vaOvbTh9GG9NF1S
y+D3t1R/c7CUkYKqB1+zr/p7ZIwGasko/A93KaI9nDrb07sy+BQoUGHb5H+qaYBo0MT17vOz
8wD7IffPSLTol9ZOELS07bcocs0LB0SCTYyhMHFq0xK3XJEeFXkhTE4HUUZWl4uY2c25AQ0E
Uqtf9gEIANDHcPxyuYo+Gv4OA7hSAIpHxhogwenIQdNwRUtZxDJTECIyKV93xhhtVRPUEzrf
KOhLKxgClY1SPjwYk9on9QZ3Ce7B2M/Jddj2JPlW10i0IcSABQebmwvk2F8/Ue06EdJKjAaq
FdGqx03vdyQA24bOfsBailXC4vPH1wT50MxojFwV+cT9LWCV3OPRcVv3LP63O9LWoSyc/CWn
BecnSmrV9BN+Coin4AHepcdwNxhMPHV8eIy9NBqFqJCFLVeSUF8y58MKKlifvAxxIS8Rsqbf
BuL852db1GH15SOiGccNaRbTOLDfm8/46rWoXvaqA+6tsWpXpwBoaNeZGUL8aB0AEQEAAYkB
JQQYAQIADwUCUqtf9gIbDAUJCWYBgAAKCRCzrgnx6aMZesyZB/wLjCeoBp9ynkamuZkRYISQ
iVotN/TEp7HyGxlyvTTLwdca8LU4w1v0V3zWIQuQTM2DJ6KmV9oH2/GmApUbg783bfZbrqOG
uThLhBBQJrYr0AxQbffYNGltX5InAEyznRNb0RsKCw4GdXSW1bK5LdpsGzzkhAxp9Onp0+yZ
IV8EQRmO6fk2wmJfFY1iV4TstcW1Twa2LL84w5HpeGA83oe+7u4DTsL1mZ6vD2f45TFmLsb5
7oW2nQ6v7XYEMKKeMWY8TLQImZefn1Z8FejO6P1TRZ/EWbQFyjAcE+4M2tjX6IJF7nIEGsLM
fwRQxlasjI+uOjBG59lUB/xncVyRQVdJ
=/vpE
-----END PGP PUBLIC KEY BLOCK-----

**Comment by AdamISZ** [comment]
I will add it to the repo, sorry for hassle.

**Comment by AdamISZ** [comment]
Added under the pubkeys/ directory. Note that the version is GnuPG not SKS so looks different. My signatures verify to the one I added. Also note it's the same key that github is using to verify commits.
